%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\urica\Dropbox\TFG_OriolCalsina\Itàlia infectats resum\Itàlia infectats resum.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 15-Sep-2024 12:31:47

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:D29";

% Specify column names and types
opts.VariableNames = ["setmanes", "s1415", "s1617", "s1718"];
opts.VariableTypes = ["string", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "setmanes", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "setmanes", "EmptyFieldRule", "auto");

% Import the data
Itliainfectatsresum = readtable("C:\Users\urica\Dropbox\TFG_OriolCalsina\Itàlia infectats resum\Itàlia infectats resum.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts