%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\urica\Dropbox\TFG_OriolCalsina\Espanya16-17\espanya1617.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 11-May-2024 16:46:24

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:G31";

% Specify column names and types
opts.VariableNames = ["Week", "CasosProcessats", "casosGrip", "Positivity", "Positivity1", "casos105HabILI", "productegrip105HabILI"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Import the data
esp1617 = readtable("C:\Users\urica\Dropbox\TFG_OriolCalsina\Espanya16-17\Ajust normal\espanya1617.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts