%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\urica\Dropbox\TFG_OriolCalsina\Itàlia 23-24\italia2324.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 03-Sep-2024 18:05:49

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:G15";

% Specify column names and types
opts.VariableNames = ["Week", "CasosProcessats", "casosGrip", "Positivity", "Positivity1", "casos105HabARI", "productegrip105HabARI"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Import the data
ital2324 = readtable("C:\Users\urica\Dropbox\TFG_OriolCalsina\Itàlia 23-24\Ajust normal\italia2324.xlsx", opts, "UseExcel", false);
Inf=ital2324.productegrip105HabARI;

%% Clear temporary variables
clear opts