%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\urica\Dropbox\TFG_OriolCalsina\Itàlia 15-16\italia1516.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 16-Jul-2024 16:33:04

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:G25";

% Specify column names and types
opts.VariableNames = ["WEEK", "CASOSPROCESSATS", "CASOSGRIP", "POSITIVITY", "POSITIVITY1", "casos105HabILI", "GRIP105HAB"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Import the data
ital1516 = readtable("C:\Users\urica\Dropbox\TFG_OriolCalsina\Itàlia 15-16\italia1516.xlsx", opts, "UseExcel", false);
Inf=ital1516.GRIP105HAB;

%% Clear temporary variables
clear opts