%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\urica\Dropbox\TFG_OriolCalsina\Espanya infectats resum\Espanya infectats resum.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 11-Sep-2024 19:55:46

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:D32";

% Specify column names and types
opts.VariableNames = ["setmanes", "s1617", "s1718", "s1819"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
Espanyainfectatsresum = readtable("C:\Users\urica\Dropbox\TFG_OriolCalsina\Espanya infectats resum\Espanya infectats resum.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts