%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\urica\Dropbox\TFG_OriolCalsina\Itàlia 16-17\italia1617.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 18-Jul-2024 22:51:36

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:G25";

% Specify column names and types
opts.VariableNames = ["WEEK", "CASOSPROCESSATS", "CASOSGRIP", "POSITIVITY", "POSITIVITY1", "casos105HabILI", "GRIP105HAB"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "WEEK", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "WEEK", "EmptyFieldRule", "auto");

% Import the data
ital1617 = readtable("C:\Users\urica\Dropbox\TFG_OriolCalsina\Itàlia 16-17\Ajust normal\italia1617.xlsx", opts, "UseExcel", false);
Inf=ital1617.GRIP105HAB;
a=0.5*ones(3,1);
Inf=[a;Inf];

%% Clear temporary variables
clear opts