%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\urica\Dropbox\TFG_OriolCalsina\Espanya18-19\espanya1819.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 22-Apr-2024 17:46:03

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:H31";

% Specify column names and types
opts.VariableNames = ["Week", "CasosProcessats", "casosGrip", "Positivity", "Positivity1", "casos105HabARI", "casos105HabILI", "productegrip105HabILI"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Week", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Week", "EmptyFieldRule", "auto");

% Import the data
esp1819 = readtable("C:\Users\urica\Dropbox\TFG_OriolCalsina\Espanya18-19\espanya1819.xlsx", opts, "UseExcel", false);
Inf=esp1819.productegrip105HabILI;
%{
dif2dies=zeros(length(Inf),1);
for z=1:length(Inf)
    if [z+2]<30
    dif2dies(z)=Inf(z+2)-Inf(z);
    end
end
for n=1:z
    if dif2dies(n)>0.30
        break
    end
end
Inf=Inf(n:end);
%}
Inf=Inf(8:end);
%% Clear temporary variables
clear opts